<?php
namespace Chatbox;

use Chatbox\Config\Config;
use Silex\Application;
use Symfony\Component\HttpFoundation\Request;


/**
 * Class Silane
 * silexラッパー。
 * デフォルトのConfigファイルをベースに、
 * デフォルトサービスの読み込みを逐次行っていく。
 *
 * コンテナに依存するメソドをガンガン生やせる無法地帯。
 *
 * @package Chatbox
 */
class Silane extends Application{

    public function __construct(array $values = array())
    {
        return parent::__construct($values); // TODO: Change the autogenerated stub
    }

    public function run(Request $request = null)
    {
        return parent::run($request); // TODO: Change the autogenerated stub
    }

	public function setConfig(Config $config){
		$this["config"] = $config;

		foreach($config->get("silane.silex",[]) as $key=>$value){
			$this[$key] = $value;
		}
		foreach($config->get("silane.controllers",[]) as $key=>$value){
			$this->mount($key,$value);
		}
		foreach($config->get("silane.providers",[]) as $key=>$value){
			$this->register($value);
		}
		$this->configure();
		return $this;
	}

	protected function configure(){

	}

	/**
	 * @return Config
	 */
	public function getConfig(){
		return $this["config"];
	}




}