<?php
namespace Chatbox;

use Chatbox\Config\Config;
use Silex\Application;

/**
 * Class Silane
 * silexの拡張
 * Config経由で主要設定を一括管理できる構成
 *
 * @package Chatbox
 */
class Silane extends Application{

    public function __construct(array $values = array())
    {
        return parent::__construct($values); // TODO: Change the autogenerated stub
    }

	public function setConfig(Config $config){
		$this["config"] = $config;

		foreach($config->get("silane.silex",[]) as $key=>$value){
			$this[$key] = $value;
		}
		foreach($config->get("silane.controllers",[]) as $key=>$value){
			$this->mount($key,$value);
		}
		foreach($config->get("silane.providers",[]) as $key=>$value){
			$this->register($value);
		}
		$this->configure();
		return $this;
	}

	protected function configure(){

	}

	/**
	 * @return Config
	 */
	public function getConfig(){
		return $this["config"];
	}




}